# Generated by Django 5.1.6 on 2025-05-12 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPUBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, default='Unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vram', models.IntegerField(help_text='VRAM in GB')),
                ('memory_type', models.CharField(choices=[('GDDR6', 'GDDR6'), ('GDDR5', 'GDDR5'), ('GDDR6X', 'GDDR6X')], max_length=20)),
                ('clock_speed', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='clock Speed (MHz)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.gpubrand')),
            ],
        ),
    ]
