# Generated by Django 5.1.6 on 2025-05-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='available',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='clock_speed',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='vram',
        ),
        migrations.AddField(
            model_name='gpu',
            name='boost_clock_mhz',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='core_clock_mhz',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_gb',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='gpu',
            name='model',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpubrand',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gpubrand',
            name='founded_year',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_type',
            field=models.CharField(choices=[('GDDR5', 'GDDR5'), ('GDDR6', 'GDDR6'), ('GDDR6X', 'GDDR6X')], default='GDDR6', max_length=10),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='gpubrand',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
