# Generated by Django 5.2 on 2025-05-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gpu_images/'),
        ),
    ]
