# Generated by Django 5.1.6 on 2025-06-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_gpu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.gpubrand'),
        ),
    ]
